### ISSUE TITLE
There is no plugin bufferline

### ISSUE THREAD

**Issue by 584sentiment** [rtgiskard/lazyNvim#1]
i found there is no plugin bufferline when i check the list of plugins,but has the config for bufferline

**Comment by rtgiskard** [comment]
Sorry for the late response, the plugin `bufferline` was removed with commit: b4bd128, but forget to clean up the keybindings config (just done with d0ab7a4, and thanks!).

For `bufferline` plugin, I'm actually just not used to it. Here is the reason to remove it from the config:

. As mouse is disabled by default, the bufferline plugin only helps as indicator, which might be a waste of space
. The header line it adds is not pretty enough, I'd like to have a more clean and minimum looking

As alternative, with telescope, the default command `buffer` with tab to auto complete, buffer switch can be completed more precise and faster with only keyboard.

Of course, you're free to add it back if you need, this config will always be kept as simple as possible, and easy to be understood and extended.
